In [2]:
import numpy as np

In [3]:
# 1. Array Bootcamp
# Create 1D array of integers
arr = np.array([10, 20, 30, 40, 50])

# Reverse the array
arr = arr[::-1]

# Compute the mean
mean = np.mean(arr)

# Cast array to 'float32'
arr = np.float32(arr)

# Display results
print(f"Array: {arr}")
print(f"Mean: {mean}")

Array: [50. 40. 30. 20. 10.]
Mean: 30.0


In [4]:
# 2. Grid Maker
# Create a 5x5 array
arr = np.zeros((5, 5), dtype=int)

# Replace border values to 1
arr[0,:] = 1
arr[4,:] = 1
arr[:,0] = 1
arr[:,4] = 1

# Display array
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [5]:
# 3. Masking 101
# Create 1D array from 0-19
arr = np.arange(20)

# Create boolean mask for odd numbers
odd_numbers = arr % 2 != 0

# Set all odd numbers to '-1'
arr[odd_numbers] = -1

# Return a boolean mask of the changed positions
print(f"Arr: {arr}")
print(f"Mask: {odd_numbers}")

Arr: [ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]
Mask: [False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True]


In [6]:
# 4. Reshape & Slice
# Create array of shape (6, 4)
arr = np.arange(24).reshape(6, 4)

# Extract the submatrix
submatrix = arr[2:5, 1:4]

# Flatten in column-major order
submatrix = submatrix.flatten(order='F')

print(f"Array: {arr}")
print(f"Submatrix: {submatrix}")

Array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Submatrix: [ 9 13 17 10 14 18 11 15 19]


In [7]:
# 5. Broadcast Warm-up
a = np.arange(5)
b = np.arange(5, 10)

# Generate a matrix where 'M[i, j] = a[i] + b[j]' using broadcasting
M = a[:, np.newaxis] + b

print(a, b)
print(M)

[0 1 2 3 4] [5 6 7 8 9]
[[ 5  6  7  8  9]
 [ 6  7  8  9 10]
 [ 7  8  9 10 11]
 [ 8  9 10 11 12]
 [ 9 10 11 12 13]]


In [8]:
# 1. Array Creation & Inspection
# Create a 1D array of 10 random floats between 0 and 1
arr = np.random.rand(10)
print(arr)

# Create a (100, 10) array of random floats (simulating 100 samples, 10 features)
arr = np.random.rand(100, 10)
# print(arr)

# Create an array of zeros with shape (5, 5) and dtype float32
arr = np.zeros((5, 5), dtype='float32')
print(arr)
print(arr.dtype)

# Generate a sequence from 0 to 1 with 20 equally spaced values.
arr = np.linspace(0, 1, 20)
print(arr)

# Check the shape, size, and dtype of a given array.
print(f"Shape: {arr.shape}")
print(f"Size: {arr.size}")
print(f"Data Type: {arr.dtype}")

[0.27439692 0.15054333 0.68790326 0.42261067 0.33597041 0.3832599
 0.32061518 0.88476449 0.97093362 0.41901672]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float32
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
Shape: (20,)
Size: 20
Data Type: float64


In [9]:
# 2. Indexing, Slicing & Masking
# Given a (6, 4) matrix, extract rows 2–4 and columns 1–3
arr = np.random.rand(24).reshape(6, 4)

submatrix = arr[2:5, 1:4]
print(arr)
print(submatrix)

# Replace all negative values in a matrix with 0
arr = np.random.randint(16, size=(4, 4))
print(arr)

# Extract only even numbers from np.arange(20) using masking
arr = np.arange(20)

even_numbers = arr % 2 == 0

print(arr[even_numbers])

# From a (5, 5) array, select the diagonal elements
arr = np.random.randint(16, size=(4,4))
diagonals = np.diagonal(arr)
print(arr)
print(f"Diagonals: {diagonals}")

# Select all rows where the last column value is greater than 0.5
arr = np.random.rand(16).reshape(4, 4)
greater = arr[:, -1] > 0.5

print(arr)
print(f">0.5: {arr[greater]}")

[[0.76192731 0.47633721 0.19689847 0.88680525]
 [0.19206563 0.15127139 0.84116322 0.45968283]
 [0.35199781 0.36729938 0.27515591 0.50127133]
 [0.30614628 0.36619778 0.31224175 0.64833435]
 [0.76760041 0.3567535  0.99429221 0.5439336 ]
 [0.59258059 0.47358926 0.72835697 0.16432104]]
[[0.36729938 0.27515591 0.50127133]
 [0.36619778 0.31224175 0.64833435]
 [0.3567535  0.99429221 0.5439336 ]]
[[ 9  7 15  2]
 [12  5 14  0]
 [13  5  7  0]
 [14  2  9 12]]
[ 0  2  4  6  8 10 12 14 16 18]
[[13 13  0 10]
 [ 2  4 14  6]
 [ 4  5 13  7]
 [ 0  4  1 15]]
Diagonals: [13  4 13 15]
[[0.35205823 0.1737972  0.89647771 0.12895029]
 [0.14346445 0.46800835 0.16023244 0.76597414]
 [0.42724695 0.22229838 0.38907079 0.00631572]
 [0.79747148 0.9615153  0.33804893 0.7973546 ]]
>0.5: [[0.14346445 0.46800835 0.16023244 0.76597414]
 [0.79747148 0.9615153  0.33804893 0.7973546 ]]


In [10]:
# 3. Reshaping & Broadcasting
# Reshape an array of shape (28, 28) into (784,)
arr = np.random.randint(784, size=(28,28)).flatten()
print(arr.shape)

# Flatten a (3, 3, 3) array into a 1D vector
arr = np.random.randint(27, size=(3, 3, 3))
arr = arr.flatten()
print(arr)

# Given a = np.arange(3) and b = np.arange(3, 6), create a matrix where M[i, j] = a[i] + b[j] using broadcasting
a = np.arange(3)
b = np.arange(3, 6)

M = a[:, np.newaxis] + b
print(a)
print(b)
print(M)

# Normalize each column of a matrix by dividing by its column max
arr = np.random.randint(9, size=(3,3)).astype('float64')
print(arr)
for i in range(arr.shape[1]):
    col_max = np.max(arr[:,i])
    arr[:,i] /= col_max
    print(col_max)

# Standardize each column: subtract mean and divide by standard deviation
arr = np.random.rand(3, 3)
print(f"Before standardization: {arr}")
for i in range(arr.shape[1]):
    mean = np.mean(arr[:,i])
    std = np.std(arr[:,i])
    arr[:,i] = (arr[:,i] - mean) / std
print(f"After standardization: {arr}")

(784,)
[14  4 10  6  8  9  3 17  0 10  8 15 21 20 17 16 26 17  0  1 23 23 23 24
 11  5 12]
[0 1 2]
[3 4 5]
[[3 4 5]
 [4 5 6]
 [5 6 7]]
[[8. 6. 3.]
 [1. 0. 0.]
 [7. 0. 7.]]
8.0
6.0
7.0
Before standardization: [[0.75277527 0.3771472  0.27732817]
 [0.13738052 0.001029   0.18554478]
 [0.06986797 0.57527304 0.88976472]]
After standardization: [[ 1.40851203  0.24912316 -0.55519846]
 [-0.5943907  -1.33015406 -0.8488181 ]
 [-0.81412133  1.0810309   1.40401656]]


In [11]:
# 4. Vectorized Computations
# Compute the mean, standard deviation, and variance of a dataset along each feature (axis=0)
arr = np.random.randint(10, size=(4,4))
mean: float = np.mean(arr, axis=0)
std: float = np.std(arr, axis=0)
variance: float = np.var(arr, axis=0)

print(arr)
print(f"Mean: {mean}\nStandard Deviation: {std}\nVariance: {variance}")

# Given two arrays y_true and y_pred, compute mean squared error (MSE) without loops
y_true = np.random.randint(2, size=(9,))
y_pred = np.random.randint(2, size=(9,))
mse = np.mean((y_true - y_pred) ** 2)
print(f"True: {y_true}\nPredictions: {y_pred}\nMSE (Mean-Squared Error): {mse}")

# Normalize a vector v so that its Euclidean norm = 1
v = [5, 6]
norm = np.linalg.norm(v)
print(f"Euclidean Norm: {norm}]")
v_normalized = v / norm

print(f"Normalized: {v_normalized}")
print("Norm of normalized vector:", np.linalg.norm(v_normalized))

# Center a dataset by subtracting its mean along each column
arr = np.random.randint(9, size=(3, 3)).astype('float64')
print(f"Original:\n{arr}")
for i in range(arr.shape[1]):
    mean = np.mean(arr[:,i])
    arr[:,i] -= mean
print(f"Centered:\n{arr}")

# Compute softmax for a 1D array
arr = np.array([2.0, 1.0, .1])

exp_arr = np.exp(arr)
softmax_arr = exp_arr / np.sum(exp_arr)
print(f"SoftMax: {softmax_arr}")

[[3 3 6 6]
 [2 1 0 7]
 [8 0 8 5]
 [4 0 7 2]]
Mean: [4.25 1.   5.25 5.  ]
Standard Deviation: [2.27760839 1.22474487 3.1124749  1.87082869]
Variance: [5.1875 1.5    9.6875 3.5   ]
True: [1 0 1 1 1 1 1 0 1]
Predictions: [1 1 0 1 0 1 1 0 0]
MSE (Mean-Squared Error): 0.4444444444444444
Euclidean Norm: 7.810249675906654]
Normalized: [0.6401844  0.76822128]
Norm of normalized vector: 1.0
Original:
[[8. 1. 3.]
 [1. 5. 8.]
 [6. 3. 5.]]
Centered:
[[ 3.         -2.         -2.33333333]
 [-4.          2.          2.66666667]
 [ 1.          0.         -0.33333333]]
SoftMax: [0.65900114 0.24243297 0.09856589]


In [32]:
# 5. Linear Algebra
# Compute the dot product of two vectors
v1 = np.array([2, 4, 6, 8, 10])
v2 = np.array([1, 3, 5, 7, 9])

dot_product = np.dot(v1, v2)
print(f"Dot Product: {dot_product}")

# Multiply two matrices A and B (where shapes align)
v1 = np.random.randint(5, size=(2,2))
v2 = np.random.randint(5, size=(2,2))

matrix_mult = v1 @ v2
print(f"Vector #1:\n{v1}")
print(f"Vector #2:\n{v2}")
print(f"Matrix Multiplication:\n{matrix_mult}")

# Compute the transpose of a matrix
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr_transpose = arr.T
print(f"Transpose: {arr_transpose}")

# Find the inverse of a 3×3 matrix
arr = np.random.randint(1, 10, size=(3, 3))
arr_inv = np.linalg.inv(arr)
identity = np.round(arr @ arr_inv).astype(int)
print(f"Arr:\n{arr}\nInverse:\n{arr_inv}\nIdentity Matrix:\n{identity}")

# Compute the Euclidean norm (L2 norm) of a vector
v = np.array([1, 2])
norm = np.linalg.norm(v)
print(f"Vector:\n{v}\nL2 Norm:\n{norm}")

# Compute the covariance matrix of a dataset X using X.T @ X / n
arr = np.random.randint(1, 6, size=(3, 3)).astype('float64')
n = arr.shape[0]

print(f"Arr:\n{arr}")
for i in range(arr.shape[1]):
    mean = np.mean(arr[:,i])
    arr[:,i] -= mean
print(f"Centered Arr:\n{arr}")
covariance = arr.T @  arr / (n - 1)
print(f"Covariance:\n{covariance}")

# Project a vector v onto another vector u
u = np.array([1,0])
v = np.array([3, 4])
projection = (np.dot(u,v) / np.dot(u,u)) * u
print(f"Projection:{projection}")

# Solve a linear system Ax = b using np.linalg.solve
A = np.array([
    [3, 1],
    [1, 2]
])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
print(f"x = {x}")

Dot Product: 190
Vector #1:
[[1 0]
 [4 4]]
Vector #2:
[[2 3]
 [1 0]]
Matrix Multiplication:
[[ 2  3]
 [12 12]]
Transpose: [[1 4]
 [2 5]
 [3 6]]
Arr:
[[8 1 1]
 [7 3 5]
 [4 3 5]]
Inverse:
[[-5.55111512e-17  3.33333333e-01 -3.33333333e-01]
 [ 2.50000000e+00 -6.00000000e+00  5.50000000e+00]
 [-1.50000000e+00  3.33333333e+00 -2.83333333e+00]]
Identity Matrix:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Vector:
[1 2]
L2 Norm:
2.23606797749979
Arr:
[[4. 4. 3.]
 [1. 1. 2.]
 [3. 3. 3.]]
Centered Arr:
[[ 1.33333333  1.33333333  0.33333333]
 [-1.66666667 -1.66666667 -0.66666667]
 [ 0.33333333  0.33333333  0.33333333]]
Covariance:
[[2.33333333 2.33333333 0.83333333]
 [2.33333333 2.33333333 0.83333333]
 [0.83333333 0.83333333 0.33333333]]
Projection:[3. 0.]
x = [2. 3.]


In [57]:
# 6. Randomness, Sampling & Initialization
# Generate random weights from a normal distribution (mean 0, std 1).
weights = np.random.normal(loc=0, scale=1, size=(3,3))
print(weights, weights.mean(), weights.std())

# Shuffle rows of a dataset.
arr = np.random.randint(1, 10, size=(5,3))
print(arr)
np.random.shuffle(arr)
print(arr)

# Split an array of shape (100, 10) into training (80%) and test (20%) sets.
arr = np.random.randint(2, size=(100,10))
split_index = int(0.8 * len(arr))
X_train = arr[:split_index]
X_test = arr[split_index:]

print(f"Training Dataset: {X_train.shape}")
print(f"Test Dataset: {X_test.shape}")

# Set a random seed to make your results reproducible.
np.random.seed(42)
arr = np.random.randint(2, size=(100,10))
split_index = int(0.8 * len(arr))
X_train = arr[:split_index]
X_test = arr[split_index:]

print(f"Training Dataset: {X_train.shape}")
print(f"Test Dataset: {X_test.shape}")

# Generate 10 random integers between 0 and 100.
rand_ints = np.random.randint(101, size=(10))
print(rand_ints)

[[-1.91270652  0.36247646  0.57134751]
 [ 0.97052382  0.74196302  1.47665863]
 [ 0.70024295 -0.13229944 -0.07361112]] 0.300510589740914 0.9122452205886977
[[1 2 1]
 [5 9 6]
 [1 1 2]
 [9 3 1]
 [5 7 6]]
[[5 9 6]
 [1 1 2]
 [5 7 6]
 [1 2 1]
 [9 3 1]]
Training Dataset: (80, 10)
Test Dataset: (20, 10)
Training Dataset: (80, 10)
Test Dataset: (20, 10)
[62 16 72 32 83 76 91 28 12 45]
