In [19]:
import numpy as np
import pandas as pd

In [ ]:
""" I. Array Creation & Initialization """
# 1,"Create a 4×4 array of zeros, then set the border to 1 using slicing."
arr=np.zeros((4,4), dtype=int)
arr[0,:]=arr[-1,:]=1 # first and last row
arr[:,0]=arr[:,-1]=1 # first and last column
# print(f"[#1]\n{arr}\n")

# 2,Generate a 5×3 array of random floats between 0 and 1. Convert to int32 and verify dtype.
arr=np.random.rand(5,3).astype('int32')
# print(f"[#2]\nMatrix:\n{arr}\nData Type: {arr.dtype}\n")

# 3,"Create an identity matrix of size 6×6, then extract the upper triangle (including diagonal)."
arr=np.eye(6, k=0, dtype=int)
# print(f"[#3]\nIdentity Matrix:\n{arr}\n")

# 4,Make a 100-element array of evenly spaced values from 0 to 10. Reshape into 10×10.
arr=np.linspace(0, 10, 100).reshape(10, 10)
# print(f"[#4]\n0-10 (evenly-spaced):\n{arr}\n")

# 5,Create a 3D array (2×3×4) filled with np.pi. Flatten it and confirm original size.
arr=np.full((2, 3, 4), fill_value=np.pi).flatten()
# print(f"[#5]\nPI:\n{arr}\nShape: {arr.shape}\nSize: {arr.size}\n")

# 6. Generate a 3×5 array of random integers between 10 and 50.
arr=np.random.randint(10, 51, size=(3, 5))
# print(f"[#6]\n{arr}\n")

# 7. Create a 1D array of 20 evenly spaced values between -5 and 5.
arr=np.linspace(-5, 5, 20)
# print(f"[#7]\n{arr}\n")

# 8. Create a 1D array of numbers from 0 to 15 with step 3.
arr=np.arange(0, 16, 3)
# print(f"[#8]\n{arr}\n")

# 9. Create a 3×3×3 array of zeros, then set the center of each 3x3 slice to 1
arr=np.zeros((3, 3, 3))
arr[:, 1, 1]=1
# print(f"[#9]\n{arr}\n")

# 10. Generate a 4×4 ones array of dtype int, then convert it to float64.
arr=np.ones((4, 4), dtype=int).astype('float64')
# print(f"[#10]\n{arr}\n")

[#9]
[[[0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]]

[#10]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]



In [140]:
""" II. Indexing, Slicing & Boolean Masking (5 problems) """
# 1,"From a 6×6 random matrix, extract the center 4×4 submatrix using slicing."
arr=np.random.randint(11, size=(6,6))
# print(f"[#1]\n{arr}\n")

# 2,"Given a 10×5 array, use boolean masking to set all values < 0.3 to 0."
arr=np.random.rand(10, 5)
mask=arr<0.3
arr[mask]=0
# print(f"[#2]\n{arr}\n")


# 3,Extract odd-indexed rows and even-indexed columns from a 8×8 array.
arr=np.random.randint(10, size=(8,8))
extracted=arr[1::2,::2]
# print(f"[#3]\n{arr}\nExtracted:\n{extracted}\n")

# 4,"Use fancy indexing to select rows [1, 3, 5] and columns [0, 2, 4] from a 7×6 matrix."
arr=np.random.randint(10, size=(7,6))
rows=[1,3,5]
cols=[0,2,4]
extracted=arr[np.ix_(rows, cols)]
# print(f"[#4]\n{arr}\nExtracted:\n{extracted}\n")

# 5,Create a checkerboard pattern (1s and 0s) in an 8×8 array using boolean indexing.
arr=np.zeros((8,8))
arr[0::2,::2]=1
arr[1::2,1::2]=1
# print(f"[#5]\n{arr}\n")

# 6. Extract the last 3 rows and last 2 columns from a 5×7 array using negative indices.
# Practice negative indexing.
arr=np.random.randint(10, size=(5,7))
extracted=arr[-3::,-2::]
# print(f"[#6]\n{arr}\nExtracted:\n{extracted}\n")

# 7. Select all elements in a 6×6 array that are greater than the mean of the array.
# Practice comparison with scalar and boolean masking.
arr=np.random.randint(10, size=(6,6))
extracted=arr>arr.mean()
selected_elements=arr[extracted]
# print(f"[#7]\n{arr}\nElements greater than the mean:\n{selected_elements}\n")

# 8. Reverse the order of rows and columns in a 4×5 array (flip upside-down and left-right).
arr=np.random.randint(10, size=(4,5))
# print(f"[#8]\n{arr}\n")
# arr=np.flip(arr)
# print(f"{arr}\n")

# 9. Replace all even numbers in a 1D array of 20 integers with -1 using boolean indexing.
arr=np.arange(20)
mask=arr % 2 == 0
arr[mask] = -1
# print(f"[#9]\n{arr}\n")

# 10. Extract a diagonal (main and offset) from a 6×6 array using slicing or np.diag.
arr=np.random.randint(10, size=(6,6))
diag=np.diag(arr)
# print(f"[#10]\n{arr}\nDiagonal:\n{diag}\n")

In [36]:
""" III. Mathematical Operations & Broadcasting (5 problems) """
# 1,"Add a row vector [10, 20, 30] to each row of a 5×3 matrix using broadcasting."
row=[10, 20, 30]
arr=np.zeros((5, 3))
arr=arr+row
# print(f"[#1]\n{arr}\n")

# 2,Compute (A - mean(A)) / std(A) for a 100×4 feature matrix (standardization).
arr=np.random.randint(6, size=(100,4))
standardization=(arr - arr.mean(axis=0)) / arr.std(axis=0)
# print(f"[#2]\n{arr}\nStandardization: {standardization}")

# 3,Multiply a 4×1 column vector with a 1×5 row vector → result should be 4×5.
arr1=np.arange(1, 5).reshape(4,1)
arr2=np.arange(1, 6).reshape(1,5)
# print(f"[#3]\n{arr1}\n{arr2}\n{arr1 * arr2}")

# 4,Compute element-wise exp(x) and log(x) on a 3×3 array of values > 1.
arr=np.random.randint(2, 10, size=(3,3))
exponent=np.exp(arr)
log=np.log(arr)
# print(f"[#4]\n{arr}\nExponent: {exponent}\nLog: {log}")


# 5,Normalize each row of a 6×4 matrix to sum to 1 (like probability distribution).
arr=np.random.rand(6,4)
normalized=(arr - arr.min(axis=0)) / (arr.max(axis=0) - arr.min(axis=0))
# print(f"[#5]\n{arr}\nNormalized:\n{normalized}")

In [42]:
""" IV. Linear Algebra Operations (4 problems) """
from scipy.linalg import hilbert

# 1,"Compute A @ B for A=(3×4), B=(4×2). Then compute A.T @ A."
a=np.random.randint(10, size=(3,4))
b=np.random.randint(10, size=(4,2))
product=a @ b
result=a.T @ a
# print(f"[#1]\na={a}\nb={b}\nProduct:\n{product}\nResult:\n{result}")


# 2,Solve Ax = b where A is 4×4 Hilbert matrix (use np.linalg.solve).
A=hilbert(4)
b=np.arange(4)
result = np.linalg.solve(A, b)
# print(f"[#2]\na={a}\nb={b}\nResult:\n{result}")

# 3,Find eigenvalues and eigenvectors of a symmetric 3×3 random matrix.
A=np.random.rand(3,3)
A_sym=(A+A.T)/2
eigvals, eigvecs = np.linalg.eig(A_sym)
# print("[#3] Symmetric Matrix A:\n", A_sym)
# print("Eigenvalues:\n", eigvals)
# print("Eigenvectors (columns):\n", eigvecs)

# 4,Compute the Moore-Penrose pseudoinverse of a 5×3 matrix and verify A @ A_pinv @ A ≈ A.
A=np.random.rand(5,3)
A_pinv=np.linalg.pinv(A)
reconstructed = A @ A_pinv @ A # verification

print("[#4] Matrix A:\n", A)
print("Pseudoinverse A_pinv:\n", A_pinv)
print("Reconstructed A (A @ A_pinv @ A):\n", reconstructed)
print("Check approximation: np.allclose(A, reconstructed) ->", np.allclose(A, reconstructed))

[#4] Matrix A:
 [[0.25499365 0.56251218 0.17736607]
 [0.36472636 0.6079525  0.71342289]
 [0.40981352 0.70938558 0.21371535]
 [0.03138434 0.8881068  0.04284386]
 [0.85505006 0.73083644 0.01059042]]
Pseudoinverse A_pinv:
 [[-0.09366589  0.03766363  0.09596234 -1.00788482  1.17239033]
 [ 0.26044852 -0.19278747  0.22840713  1.02793629 -0.14263899]
 [ 0.04215941  1.42697366  0.01370843 -0.51334353 -0.6089845 ]]
Reconstructed A (A @ A_pinv @ A):
 [[0.25499365 0.56251218 0.17736607]
 [0.36472636 0.6079525  0.71342289]
 [0.40981352 0.70938558 0.21371535]
 [0.03138434 0.8881068  0.04284386]
 [0.85505006 0.73083644 0.01059042]]
Check approximation: np.allclose(A, reconstructed) -> True


In [29]:
""" V. Statistical Functions & Aggregation (5 problems) """
from scipy.stats import mode
# 1,"For a 1000-sample normal distribution, compute mean, median, and mode (use scipy.stats)."
arr=np.random.normal(loc=0, scale=1, size=(1000,))
mean=arr.mean()
median=np.median(arr)
mode=mode(arr, keepdims=True)
# print(f"[#1]\nMean: {mean:.4f}\nMedian: {median:.4f}\nMode: {mode.mode[0]:.4f} (count={mode.count[0]})\n")

# 2,"In a 10×5 feature matrix, compute column-wise z-scores: (x - μ) / σ."
arr=np.random.rand(10, 5)
z_score=(arr - arr.mean(axis=0)) / arr.std(axis=0)
# print(f"[#2]\narr:\n{arr}\nz-score: {z_score}")

# 3,Compute rolling standard deviation (window=3) along axis=0 for a 20×3 array.
arr=pd.DataFrame(np.random.randint(10, size=(20,3)))
rolling_std=arr.rolling(window=3).std()
# print(f"[#3]Rolling σ:\n{rolling_std}")

# 4,Find correlation matrix of a 50×4 dataset. Mask correlations > 0.8.
arr=pd.DataFrame(np.random.randint(10, size=(50,4)))
corr_matrix=arr.corr()
mask= corr_matrix > 0.8
# print(f"[#4]\nCorrelation Matrix:\n{corr_matrix}\nMask (correlations > 0.8):\n{mask}")

# 5,Replace values > 3σ from column mean with the median (outlier capping).
arr=np.random.randint(100, size=(10,10))

mean = arr.mean(axis=0)
std = arr.std(axis=0)
median = np.median(arr, axis=0)

mask = arr > (mean + 3*std) # Create mask where elements exceed mean + 3*std
arr[mask] = np.take(median, np.where(mask)[1]) # Replace outliers with the column median

# print(f"\nCapped:\n{arr}")

In [ ]:
""" VI. Reshaping, Transposing, Flattening (4 problems) """
# 1,"Reshape a 36-element array into 3×3×4, then transpose to 4×3×3."
arr=np.arange(36).reshape(3,3,4)
arr_transpose=np.transpose(arr, axes=(2,1,0))
# print(f"[#1]\n{arr}")

# 2,Flatten a 5×5×5 cube in C-order vs F-order. Compare results.
arr=np.random.randint(10, size=(5,5,5))
c_flat=arr.flatten(order='C')
f_flat=arr.flatten(order='F')
# print(f"[#2]\nC-order:\n{c_flat}\nF-order:\n{f_flat}")

# 3,"Stack three 3×3 matrices vertically, then horizontally."
a=np.random.randint(10, size=(3,3))
b=np.random.randint(10, size=(3,3))
c=np.random.randint(10, size=(3,3))
vertical_stack=np.vstack([a,b,c])
horizontal_stack=np.hstack([a,b,c])
# print(f"[#3]\nVStack:\n{vertical_stack}\nHStack:\n{horizontal_stack}")

# 4,Use np.tile to repeat a 2×2 pattern into an 8×8 grid.
tile=np.ones((2,2), dtype=int)
grid=np.tile(tile, (4,4))
print(f"[#4]\ntile:\n{tile}\ngrid:\n{grid}")


[#4]
tile:
[[1 1]
 [1 1]]
grid:
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [ ]:
""" VII. Vectorization & Performance (3 problems) """
# 1,Compute pairwise Euclidean distances between 100 points in 2D (no loops).


# 2,Vectorize f(x) = x^3 + sin(x) and apply to 1 million points. Time vs loop.


# 3,"Create x, y meshgrid (50×50), compute z = x^2 + y^2, find min/max locations."

