In [2]:
import numpy as np

In [ ]:
""" I. Array Creation & Initialization """
# 1,"Create a 4×4 array of zeros, then set the border to 1 using slicing."
arr=np.zeros((4,4), dtype=int)
arr[0,:]=arr[-1,:]=1 # first and last row
arr[:,0]=arr[:,-1]=1 # first and last column
# print(f"[#1]\n{arr}\n")

# 2,Generate a 5×3 array of random floats between 0 and 1. Convert to int32 and verify dtype.
arr=np.random.rand(5,3).astype('int32')
# print(f"[#2]\nMatrix:\n{arr}\nData Type: {arr.dtype}\n")

# 3,"Create an identity matrix of size 6×6, then extract the upper triangle (including diagonal)."
arr=np.eye(6, k=0, dtype=int)
# print(f"[#3]\nIdentity Matrix:\n{arr}\n")

# 4,Make a 100-element array of evenly spaced values from 0 to 10. Reshape into 10×10.
arr=np.linspace(0, 10, 100).reshape(10, 10)
# print(f"[#4]\n0-10 (evenly-spaced):\n{arr}\n")

# 5,Create a 3D array (2×3×4) filled with np.pi. Flatten it and confirm original size.
arr=np.full((2, 3, 4), fill_value=np.pi).flatten()
# print(f"[#5]\nPI:\n{arr}\nShape: {arr.shape}\nSize: {arr.size}\n")

# 6. Generate a 3×5 array of random integers between 10 and 50.
arr=np.random.randint(10, 51, size=(3, 5))
# print(f"[#6]\n{arr}\n")

# 7. Create a 1D array of 20 evenly spaced values between -5 and 5.
arr=np.linspace(-5, 5, 20)
# print(f"[#7]\n{arr}\n")

# 8. Create a 1D array of numbers from 0 to 15 with step 3.
arr=np.arange(0, 16, 3)
# print(f"[#8]\n{arr}\n")

# 9. Create a 3×3×3 array of zeros, then set the center of each 3x3 slice to 1
arr=np.zeros((3, 3, 3))
arr[:, 1, 1]=1
# print(f"[#9]\n{arr}\n")

# 10. Generate a 4×4 ones array of dtype int, then convert it to float64.
arr=np.ones((4, 4), dtype=int).astype('float64')
# print(f"[#10]\n{arr}\n")

[#9]
[[[0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]]

[#10]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]



In [ ]:
""" II. Indexing, Slicing & Boolean Masking (5 problems) """
# 1,"From a 6×6 random matrix, extract the center 4×4 submatrix using slicing."
arr=np.random.randint(11, size=(6,6))
# print(f"[#1]\n{arr}\n")

# 2,"Given a 10×5 array, use boolean masking to set all values < 0.3 to 0."
arr=np.random.rand(10, 5)
mask=arr<0.3
arr[mask]=0
# print(f"[#2]\n{arr}\n")


# 3,Extract odd-indexed rows and even-indexed columns from a 8×8 array.
arr=np.random.randint(10, size=(8,8))
extracted=arr[1::2,::2]
# print(f"[#3]\n{arr}\nExtracted:\n{extracted}\n")

# 4,"Use fancy indexing to select rows [1, 3, 5] and columns [0, 2, 4] from a 7×6 matrix."
arr=np.random.randint(10, size=(7,6))
rows=[1,3,5]
cols=[0,2,4]
extracted=arr[np.ix_(rows, cols)]
print(f"[#4]\n{arr}\nExtracted:\n{extracted}\n")

# 5,Create a checkerboard pattern (1s and 0s) in an 8×8 array using boolean indexing.


# 6. Extract the last 3 rows and last 2 columns from a 5×7 array using negative indices.
# Practice negative indexing.

# 7. Select all elements in a 6×6 array that are greater than the mean of the array.
# Practice comparison with scalar and boolean masking.

# 8. Reverse the order of rows and columns in a 4×5 array (flip upside-down and left-right).

# 9. Replace all even numbers in a 1D array of 20 integers with -1 using boolean indexing.

# 10. Extract a diagonal (main and offset) from a 6×6 array using slicing or np.diag.

[#4]
[[8 5 9 1 7 1]
 [0 0 8 1 6 1]
 [3 5 1 3 5 0]
 [6 5 7 2 3 6]
 [2 6 8 3 6 0]
 [9 5 8 0 7 2]
 [3 0 8 5 2 3]]

Extracted:
[[0 8 6]
 [6 7 3]
 [9 8 7]]



In [ ]:
""" III. Mathematical Operations & Broadcasting (5 problems) """
# 1,"Add a row vector [10, 20, 30] to each row of a 5×3 matrix using broadcasting."


# 2,Compute (A - mean(A)) / std(A) for a 100×4 feature matrix (standardization).


# 3,Multiply a 4×1 column vector with a 1×5 row vector → result should be 4×5.


# 4,Compute element-wise exp(x) and log(x) on a 3×3 array of values > 1.


# 5,Normalize each row of a 6×4 matrix to sum to 1 (like probability distribution).



In [ ]:
""" IV. Linear Algebra Operations (4 problems) """
# 1,"Compute A @ B for A=(3×4), B=(4×2). Then compute A.T @ A."


# 2,Solve Ax = b where A is 4×4 Hilbert matrix (use np.linalg.solve).


# 3,Find eigenvalues and eigenvectors of a symmetric 3×3 random matrix.


# 4,Compute the Moore-Penrose pseudoinverse of a 5×3 matrix and verify A @ A_pinv @ A ≈ A.



In [ ]:
""" V. Statistical Functions & Aggregation (5 problems) """
# 1,"For a 1000-sample normal distribution, compute mean, median, and mode (use scipy.stats)."


# 2,"In a 10×5 feature matrix, compute column-wise z-scores: (x - μ) / σ."


# 3,Compute rolling standard deviation (window=3) along axis=0 for a 20×3 array.


# 4,Find correlation matrix of a 50×4 dataset. Mask correlations > 0.8.


# 5,Replace values > 3σ from column mean with the median (outlier capping).



In [ ]:
""" VI. Reshaping, Transposing, Flattening (4 problems) """
# 1,"Reshape a 36-element array into 3×3×4, then transpose to 4×3×3."


# 2,Flatten a 5×5×5 cube in C-order vs F-order. Compare results.


# 3,"Stack three 3×3 matrices vertically, then horizontally."


# 4,Use np.tile to repeat a 2×2 pattern into an 8×8 grid.



In [ ]:
""" VII. Vectorization & Performance (3 problems) """
# 1,Compute pairwise Euclidean distances between 100 points in 2D (no loops).


# 2,Vectorize f(x) = x^3 + sin(x) and apply to 1 million points. Time vs loop.


# 3,"Create x, y meshgrid (50×50), compute z = x^2 + y^2, find min/max locations."

